version: 6
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /stylesheets
  static_dir: stylesheets
  secure: always
  login: required

- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: app.application
  secure: always
  login: required

libraries:
- name: MySQLdb
  version: "latest"
- name: webapp2
  version: "latest"
- name: jinja2
  version: "latest"